# Generated by Django 4.2.7 on 2024-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume_manager", "0006_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
