# Generated by Django 4.2.7 on 2023-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_description",
            name="brief_stat",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
