# Generated by Django 4.2.7 on 2023-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_manager", "0002_job_description_brief_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_description",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
